
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import FooterSection from "../components/FooterSection";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Restaurant App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>


            {/* <NavBar /> */}

            {children}
            <FooterSection />
        </>

    );
}
